spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-fail: payment-fail
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  application:
    name: saga-payment-service

server:
  port: 8091

#logging:
#  level:
#    org:
#      apache:
#        kafka: OFF